language: node_js
node_js:
- '7'
deploy:
  provider: heroku
  api_key:
    secure: vEX3i5xiMnh4ldh2mwTu1PR/qjoOIDd2fXcn6fGVPlubCeLRadsrcO/Fx+L8Zpj/cmP/a4bl2ni5EmiHB5WurqJ+y/jp5k92QqIwwcgmjm2LB+asft2O5luzLJ6aD9t0Vx+Ertw43GKs/9VXTx1Z2qbWQCUDockjPNXDFZ04dDvjkzkXZKYF6JdrXkXqXKzR4OoEYkXyY0jTCWKN3Dh++a+LFgtLe3JX6Ax2Oe5QR8B9a7CTpW6Jt1S/gFBTF+j0+UAC+LWfqDInvEniGrcDQn4Z+Kehv+Sn1N0Hf+A2zAiWHnXYoDrZlDBvIPJGwhyr1amZlmsltT015FIg0JQh/fbOStvg+iO+mdXA2awD4PYRXbnUJXO6DC7qlYJwyhLmzMv8xt0wvkHDG30X0Tx1qOlqfled+QhdJO1Y9Y2fp7jzkS0KKOSpH/PV2MorzzBH09p1CcfGrP9hNKw/o1c5DbPs8z/BtnFwNoRXEHAR5KNbzZ7NL/l5zpWYIANkTW+7X6WTDJ+LltkvJakIMpAaP0oL/Y5nIT0e3F5djgZRgO+ym0lOy5f8aG69np6kFwMUsN0NFF+rbgNwgrAVsPvDTyRx2Ngc01FIXSbqjst2sdpilTuH3Lmn8Qpw0qxYq0BK58+kabYO+LqeIXMKbCV2CeQHz5dw/5ng6M/K889lJaM=
  app: murmuring-bayou-68966
